USE [master]
GO

/****** Object:  Database [PaymentDetailDB]    Script Date: 3/19/2020 7:11:54 AM ******/
CREATE DATABASE [PaymentDetailDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PaymentDetailDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PaymentDetailDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PaymentDetailDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PaymentDetailDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PaymentDetailDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PaymentDetailDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PaymentDetailDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PaymentDetailDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PaymentDetailDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PaymentDetailDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PaymentDetailDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PaymentDetailDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PaymentDetailDB] SET  MULTI_USER 
GO

ALTER DATABASE [PaymentDetailDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PaymentDetailDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PaymentDetailDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PaymentDetailDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PaymentDetailDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PaymentDetailDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PaymentDetailDB] SET  READ_WRITE 
GO

